### ISSUE TITLE
API Error handling

### ISSUE THREAD

**Issue by isaacsanders** [isaacsanders/githubris#13]
Github defines a couple of errors that can occur with the API.

Should these raise exceptions? Or is there a better idea?

cc: @zspencer

**Comment by zspencer** [comment]
Exception seems reasonable for now.

**Comment by isaacsanders** [comment]
mk. Should they be custom error classes?

**Comment by zspencer** [comment]
They should reveal their intent ;)

## 

Zee

**Comment by isaacsanders** [comment]
mk. Thanks!

**Comment by isaacsanders** [comment]
I think I need to take care of this, but I already am working on Authentication, which seems dependent on Error handling. Does it make sense to do this first?

**Comment by isaacsanders** [comment]
It does stuff now... I hope it does it well. I will push up for review.

**Comment by isaacsanders** [comment]
I like the current strategy, going out tonight with the other updates.
